// This file (and this file only) has been generated by Claude Fable 5.

//! Parsing and running of TPTP UEQ (unit equality) problems.
//!
//! The entry points are [`run_tptp_ueq`] and [`run_tptp_ueq_with_limits`].
//! A TPTP file is parsed with the `tptp` crate, every unit equality literal is
//! translated into a curried `SimpleLang` term
//! (`f(t1,...,tn)  ~>  (app ... (app f t1') ... tn')`), and the resulting set of
//! equations is handed to the [`Runner`].
//!
//! Disequalities (`s != t`, or `~ s = t`) are controlled by the boolean
//! parameter `disequality_as_equality`:
//! * `true`:  the disequality is added as if it were the equation `s = t`,
//! * `false`: the disequality is ignored (only counted).

use crate::*;
// `slotted_egraphs` also exports a `Runner`; we want the one from runner.rs.
use crate::runner::Runner;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::time::Duration;

use tptp::cnf;
use tptp::fof;
use tptp::top;
use tptp::TPTPIterator;

/// A TPTP UEQ problem, translated to `SimpleLang`.
pub struct UeqProblem {
    /// Equations as pairs of s-expressions parsable by `RecExpr::<SimpleLang>::parse`.
    pub equations: Vec<(String, String)>,
    /// Symbols of the problem together with their arity (constants have arity 0).
    pub symbol_list: Vec<(String, u8)>,
    /// Number of disequalities encountered in the problem.
    /// Depending on `disequality_as_equality` they were either ignored or
    /// added to `equations`.
    pub num_disequalities: usize,
}

/// Parse a TPTP UEQ problem file and run the CCX procedure on it,
/// with the default limits of [`Runner`] (`max = 10`, 30 iterations,
/// 10_000 nodes, 60 seconds).
///
/// If `disequality_as_equality` is `true`, every disequality of the problem is
/// treated as if it were an equality; otherwise disequalities are ignored.
///
/// Returns the report together with the final e-graph.
pub fn run_tptp_ueq(
    path: impl AsRef<Path>,
    disequality_as_equality: bool,
) -> Result<(CCXReport, MyEGraph), String> {
    run_tptp_ueq_with_limits(path, disequality_as_equality, 10, 30, 10_000, Duration::from_secs(60))
}

/// Same as [`run_tptp_ueq`], but with explicit limits:
/// `max_size` is the maximal analysis value ("term size") considered by the
/// procedure, the remaining parameters bound the run itself.
pub fn run_tptp_ueq_with_limits(
    path: impl AsRef<Path>,
    disequality_as_equality: bool,
    max_size: u64,
    iter_limit: usize,
    node_limit: usize,
    time_limit: Duration,
) -> Result<(CCXReport, MyEGraph), String> {
    let problem = parse_tptp_ueq(path.as_ref(), disequality_as_equality)?;
    run_ueq_problem(&problem, max_size, iter_limit, node_limit, time_limit)
}

/// Run an already-translated [`UeqProblem`] through the [`Runner`].
pub fn run_ueq_problem(
    problem: &UeqProblem,
    max_size: u64,
    iter_limit: usize,
    node_limit: usize,
    time_limit: Duration,
) -> Result<(CCXReport, MyEGraph), String> {
    let mut runner: Runner<(), String> = Runner::new(SizeAnalysisNoApp)
        .with_iter_limit(iter_limit)
        .with_node_limit(node_limit)
        .with_time_limit(time_limit);
    runner.max = max_size;
    runner.symbol_list = problem.symbol_list.clone();

    // Add every equation to the e-graph (same initialization as `ccx` in main.rs).
    for (l, r) in &problem.equations {
        let rl: RecExpr<SimpleLang> = RecExpr::parse(l)
            .map_err(|e| format!("internal error: generated expression `{l}` does not parse: {e:?}"))?;
        let rr: RecExpr<SimpleLang> = RecExpr::parse(r)
            .map_err(|e| format!("internal error: generated expression `{r}` does not parse: {e:?}"))?;
        let cl = runner.egraph.add_syn_expr(rl);
        let cr = runner.egraph.add_syn_expr(rr);
        runner.egraph.union(&cl, &cr);
        runner.us.push_back(cl);
    }

    // Add the single-deduction classes f($var_0, ..., $var_{n-1}).
    for (f, n) in &problem.symbol_list {
        let mut s = f.clone();
        for i in 0..*n {
            s = format!("(app {} (var $var_{}))", s, i);
        }
        let re: RecExpr<SimpleLang> = RecExpr::parse(&s)
            .map_err(|e| format!("internal error: generated expression `{s}` does not parse: {e:?}"))?;
        let cf = runner.egraph.add_syn_expr(re);
        runner.wo.push_back(cf);
    }

    runner.egraph.rebuild();
    update(&runner.egraph, &mut runner.wo);
    update(&runner.egraph, &mut runner.us);
    wo_no_us(&mut runner.wo, &runner.us);

    // Nothing to process (e.g. the file only contained disequalities that were
    // ignored). `Runner::run` would panic on an empty `us`, so report directly.
    if runner.us.is_empty() {
        let report = CCXReport {
            iterations: 0,
            stop_reason: CCXStopReason::EmptyUs,
            egraph_nodes: runner.egraph.total_number_of_nodes(),
            egraph_classes: runner.egraph.ids().len(),
            total_time: 0.0,
        };
        return Ok((report, runner.egraph));
    }

    let report = runner.run();
    Ok((report, runner.egraph))
}

/// Parse a TPTP file (following `include` directives) into a [`UeqProblem`].
///
/// Supported inputs:
/// * `cnf` formulas that are unit clauses `s = t` or `s != t`,
/// * `fof` formulas of the shape `![X,...]: s = t` (possibly without
///   quantifier, possibly `s != t`). For a `conjecture`, the universally
///   quantified variables are replaced by fresh Skolem constants and the
///   equation is treated as a disequality (as its negation is what a refutation
///   prover would work with).
pub fn parse_tptp_ueq(path: &Path, disequality_as_equality: bool) -> Result<UeqProblem, String> {
    let mut st = SymbolTable::default();
    let mut equations = Vec::new();
    let mut num_disequalities = 0usize;
    parse_file(
        path,
        disequality_as_equality,
        &mut st,
        &mut equations,
        &mut num_disequalities,
    )?;
    Ok(UeqProblem {
        equations,
        symbol_list: st.into_symbol_list(),
        num_disequalities,
    })
}

// ---------------------------------------------------------------------------
// symbol table
// ---------------------------------------------------------------------------

/// Keeps track of the (sanitized) symbols of the problem and their arities.
#[derive(Default)]
struct SymbolTable {
    /// TPTP name -> sanitized SimpleLang name
    renaming: HashMap<String, String>,
    /// sanitized names already in use (to avoid collisions introduced by sanitizing)
    used: HashSet<String>,
    /// sanitized name -> arity, plus insertion order
    arities: HashMap<String, u8>,
    order: Vec<String>,
    /// counter for fresh Skolem constants
    skolem_counter: usize,
}

impl SymbolTable {
    /// Register the TPTP functor `raw` with the given arity and return the
    /// sanitized name to be used in `SimpleLang` expressions.
    fn register(&mut self, raw: &str, arity: usize) -> Result<String, String> {
        let arity: u8 = arity
            .try_into()
            .map_err(|_| format!("symbol `{raw}` has arity {arity}, which exceeds u8"))?;
        let name = match self.renaming.get(raw) {
            Some(name) => name.clone(),
            None => {
                let mut name = sanitize_symbol(raw);
                // sanitizing may map two different TPTP names to the same string
                while self.used.contains(&name) {
                    name.push('_');
                }
                self.used.insert(name.clone());
                self.renaming.insert(raw.to_string(), name.clone());
                self.arities.insert(name.clone(), arity);
                self.order.push(name.clone());
                return Ok(name);
            }
        };
        let known = self.arities[&name];
        if known != arity {
            return Err(format!(
                "symbol `{raw}` is used with two different arities ({known} and {arity})"
            ));
        }
        Ok(name)
    }

    /// Create a fresh Skolem constant (arity 0) and return its name.
    fn fresh_skolem(&mut self) -> String {
        loop {
            let candidate = format!("sk_{}", self.skolem_counter);
            self.skolem_counter += 1;
            if !self.used.contains(&candidate) {
                self.used.insert(candidate.clone());
                self.arities.insert(candidate.clone(), 0);
                self.order.push(candidate.clone());
                return candidate;
            }
        }
    }

    fn into_symbol_list(self) -> Vec<(String, u8)> {
        self.order
            .into_iter()
            .map(|name| {
                let a = self.arities[&name];
                (name, a)
            })
            .collect()
    }
}

/// Make a TPTP atomic word usable as a `SimpleLang` symbol:
/// only `[a-zA-Z0-9_]`, no leading digit (would parse as a `Number`),
/// and not one of the reserved words of the language.
fn sanitize_symbol(raw: &str) -> String {
    let trimmed = raw.trim_matches('\'');
    let mut s: String = trimmed
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    if s.is_empty() {
        s = "_c".to_string();
    }
    if s.chars().next().unwrap().is_ascii_digit() {
        s = format!("n_{s}");
    }
    if s == "app" || s == "var" {
        s = format!("{s}_sym");
    }
    s
}

/// Slot name for a TPTP variable (TPTP variables start with an upper case
/// letter, so lowering them is injective).
fn slot_of_variable(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect::<String>()
        .to_lowercase();
    if s.is_empty() {
        s = "v".to_string();
    }
    format!("$v_{s}")
}

// ---------------------------------------------------------------------------
// file / formula traversal
// ---------------------------------------------------------------------------

fn parse_file(
    path: &Path,
    disequality_as_equality: bool,
    st: &mut SymbolTable,
    equations: &mut Vec<(String, String)>,
    num_disequalities: &mut usize,
) -> Result<(), String> {
    let bytes = fs::read(path).map_err(|e| format!("cannot read `{}`: {e}", path.display()))?;
    let mut parser = TPTPIterator::<()>::new(&bytes);
    for input in &mut parser {
        let input = input.map_err(|_| format!("syntax error in `{}`", path.display()))?;
        match input {
            top::TPTPInput::Include(include) => {
                let name = include.file_name.0 .0.to_string();
                let resolved = resolve_include(path, &name)?;
                parse_file(&resolved, disequality_as_equality, st, equations, num_disequalities)?;
            }
            top::TPTPInput::Annotated(annotated) => match *annotated {
                top::AnnotatedFormula::Cnf(c) => {
                    handle_cnf(&c.0.formula, disequality_as_equality, st, equations, num_disequalities)?;
                }
                top::AnnotatedFormula::Fof(f) => {
                    let role = f.0.role.0 .0.to_string();
                    handle_fof(&role, &f.0.formula, disequality_as_equality, st, equations, num_disequalities)?;
                }
                top::AnnotatedFormula::Tfx(_) => {
                    return Err("TFF/TFX formulas are not supported (UEQ problems are CNF or FOF)".to_string());
                }
            },
        }
    }
    if !parser.remaining.is_empty() {
        return Err(format!(
            "could not parse `{}` completely; it fails around: {}",
            path.display(),
            String::from_utf8_lossy(&parser.remaining[..parser.remaining.len().min(60)])
        ));
    }
    Ok(())
}

/// Resolve an `include('...')` directive: first relative to the including
/// file, then relative to its parent (TPTP problems include `Axioms/...`
/// relative to the TPTP root), then relative to `$TPTP`.
fn resolve_include(including_file: &Path, name: &str) -> Result<PathBuf, String> {
    let name = name.trim_matches('\'');
    let mut candidates: Vec<PathBuf> = Vec::new();
    if let Some(dir) = including_file.parent() {
        candidates.push(dir.join(name));
        // TPTP layout: Problems/XYZ/problem.p includes Axioms/xyz.ax
        if let Some(gp) = dir.parent() {
            candidates.push(gp.join(name));
            if let Some(ggp) = gp.parent() {
                candidates.push(ggp.join(name));
            }
        }
    }
    if let Ok(root) = std::env::var("TPTP") {
        candidates.push(Path::new(&root).join(name));
    }
    for c in &candidates {
        if c.is_file() {
            return Ok(c.clone());
        }
    }
    Err(format!(
        "cannot resolve include `{name}`; tried {:?} (you can set the TPTP environment variable to the TPTP root)",
        candidates
    ))
}

fn add_equation(
    left: &fof::Term,
    right: &fof::Term,
    st: &mut SymbolTable,
    skolemized: &HashMap<String, String>,
    equations: &mut Vec<(String, String)>,
) -> Result<(), String> {
    let l = term_to_sexpr(left, st, skolemized)?;
    let r = term_to_sexpr(right, st, skolemized)?;
    equations.push((l, r));
    Ok(())
}

fn handle_disequality(
    left: &fof::Term,
    right: &fof::Term,
    disequality_as_equality: bool,
    st: &mut SymbolTable,
    skolemized: &HashMap<String, String>,
    equations: &mut Vec<(String, String)>,
    num_disequalities: &mut usize,
) -> Result<(), String> {
    *num_disequalities += 1;
    if disequality_as_equality {
        add_equation(left, right, st, skolemized, equations)?;
    }
    Ok(())
}

fn handle_cnf(
    formula: &cnf::Formula,
    disequality_as_equality: bool,
    st: &mut SymbolTable,
    equations: &mut Vec<(String, String)>,
    num_disequalities: &mut usize,
) -> Result<(), String> {
    let disjunction = match formula {
        cnf::Formula::Disjunction(d) => d,
        cnf::Formula::Parenthesised(d) => d,
    };
    if disjunction.0.len() != 1 {
        return Err(format!(
            "clause `{formula}` is not a unit clause; this is not a UEQ problem"
        ));
    }
    let no_skolem = HashMap::new();
    match &disjunction.0[0] {
        cnf::Literal::Atomic(atom) => {
            let (l, r) = atom_as_equality(atom)?;
            add_equation(l, r, st, &no_skolem, equations)
        }
        cnf::Literal::NegatedAtomic(atom) => {
            let (l, r) = atom_as_equality(atom)?;
            handle_disequality(l, r, disequality_as_equality, st, &no_skolem, equations, num_disequalities)
        }
        cnf::Literal::Infix(diseq) => handle_disequality(
            &diseq.left,
            &diseq.right,
            disequality_as_equality,
            st,
            &no_skolem,
            equations,
            num_disequalities,
        ),
    }
}

fn atom_as_equality<'a, 'b>(
    atom: &'a fof::AtomicFormula<'b>,
) -> Result<(&'a fof::Term<'b>, &'a fof::Term<'b>), String> {
    match atom {
        fof::AtomicFormula::Defined(fof::DefinedAtomicFormula::Infix(eq)) => {
            Ok((&eq.left, &eq.right))
        }
        _ => Err(format!(
            "atom `{atom}` is not an equality; this is not a UEQ problem"
        )),
    }
}

/// Handle a FOF formula of the shape `![X,...]: s = t` / `s = t` / `s != t`
/// (nested universal quantifiers are allowed). For a `conjecture`, the
/// universally quantified variables are Skolemized and the equation is treated
/// as a disequality, since the prover works with the negated conjecture.
fn handle_fof(
    role: &str,
    formula: &fof::Formula,
    disequality_as_equality: bool,
    st: &mut SymbolTable,
    equations: &mut Vec<(String, String)>,
    num_disequalities: &mut usize,
) -> Result<(), String> {
    let is_conjecture = role == "conjecture";
    // collect the universally quantified variables while descending to the atom
    let mut bound: Vec<String> = Vec::new();
    let (atom_eq, negated) = peel_fof(&formula.0, &mut bound)?;

    // In a conjecture, the negation turns the universal variables into
    // existential ones, i.e. into fresh Skolem constants.
    let mut skolemized: HashMap<String, String> = HashMap::new();
    if is_conjecture {
        for v in &bound {
            skolemized.insert(v.clone(), st.fresh_skolem());
        }
    }

    // A conjecture `s = t` behaves like the disequality `s != t` (and vice versa).
    let as_disequality = negated ^ is_conjecture;
    let (l, r) = atom_eq;
    if as_disequality {
        handle_disequality(l, r, disequality_as_equality, st, &skolemized, equations, num_disequalities)
    } else {
        add_equation(l, r, st, &skolemized, equations)
    }
}

/// Descend through (parenthesised, universally quantified) FOF structure and
/// return the equality atom, together with a flag telling whether it appeared
/// as a disequality (`s != t` or `~ s = t`).
fn peel_fof<'a, 'b>(
    f: &'a fof::LogicFormula<'b>,
    bound: &mut Vec<String>,
) -> Result<((&'a fof::Term<'b>, &'a fof::Term<'b>), bool), String> {
    match f {
        fof::LogicFormula::Unitary(u) => peel_fof_unitary(u, bound),
        fof::LogicFormula::Unary(u) => peel_fof_unary(u, bound),
        fof::LogicFormula::Binary(_) => Err(format!(
            "FOF formula `{f}` contains a binary connective; only unit equalities are supported"
        )),
    }
}

fn peel_fof_unit<'a, 'b>(
    f: &'a fof::UnitFormula<'b>,
    bound: &mut Vec<String>,
) -> Result<((&'a fof::Term<'b>, &'a fof::Term<'b>), bool), String> {
    match f {
        fof::UnitFormula::Unitary(u) => peel_fof_unitary(u, bound),
        fof::UnitFormula::Unary(u) => peel_fof_unary(u, bound),
    }
}

fn peel_fof_unitary<'a, 'b>(
    f: &'a fof::UnitaryFormula<'b>,
    bound: &mut Vec<String>,
) -> Result<((&'a fof::Term<'b>, &'a fof::Term<'b>), bool), String> {
    match f {
        fof::UnitaryFormula::Quantified(q) => {
            match q.quantifier {
                fof::Quantifier::Forall => (),
                fof::Quantifier::Exists => {
                    return Err(
                        "existential quantification is not supported; only `![...]:` prefixes are"
                            .to_string(),
                    )
                }
            }
            for v in &q.bound.0 {
                bound.push(v.to_string());
            }
            peel_fof_unit(&q.formula, bound)
        }
        fof::UnitaryFormula::Atomic(a) => Ok((atom_as_equality(a)?, false)),
        fof::UnitaryFormula::Parenthesised(inner) => peel_fof(inner, bound),
    }
}

fn peel_fof_unary<'a, 'b>(
    f: &'a fof::UnaryFormula<'b>,
    bound: &mut Vec<String>,
) -> Result<((&'a fof::Term<'b>, &'a fof::Term<'b>), bool), String> {
    match f {
        // `~ phi`
        fof::UnaryFormula::Unary(_, inner) => {
            let ((l, r), negated) = peel_fof_unit(inner, bound)?;
            Ok(((l, r), !negated))
        }
        // `s != t`
        fof::UnaryFormula::InfixUnary(diseq) => Ok(((&diseq.left, &diseq.right), true)),
    }
}

// ---------------------------------------------------------------------------
// term translation
// ---------------------------------------------------------------------------

/// Translate a TPTP term into a curried `SimpleLang` s-expression:
/// `f(t1,...,tn)` becomes `(app ... (app f t1') ... tn')`, a constant `c`
/// stays `c`, and a variable `X` becomes `(var $v_x)` (or its Skolem constant).
fn term_to_sexpr(
    term: &fof::Term,
    st: &mut SymbolTable,
    skolemized: &HashMap<String, String>,
) -> Result<String, String> {
    match term {
        fof::Term::Variable(v) => {
            let name = v.to_string();
            match skolemized.get(&name) {
                Some(sk) => Ok(sk.clone()),
                None => Ok(format!("(var {})", slot_of_variable(&name))),
            }
        }
        fof::Term::Function(ft) => match &**ft {
            fof::FunctionTerm::Plain(pt) => plain_term_to_sexpr(pt, st, skolemized),
            fof::FunctionTerm::Defined(d) => Err(format!(
                "defined term `{d}` (numbers, $-terms) is not supported"
            )),
            fof::FunctionTerm::System(s) => {
                Err(format!("system term `{s}` is not supported"))
            }
        },
    }
}

fn plain_term_to_sexpr(
    term: &fof::PlainTerm,
    st: &mut SymbolTable,
    skolemized: &HashMap<String, String>,
) -> Result<String, String> {
    match term {
        fof::PlainTerm::Constant(c) => st.register(&c.to_string(), 0),
        fof::PlainTerm::Function(functor, args) => {
            let name = st.register(&functor.to_string(), args.0.len())?;
            let mut s = name;
            for arg in &args.0 {
                let arg_s = term_to_sexpr(arg, st, skolemized)?;
                s = format!("(app {s} {arg_s})");
            }
            Ok(s)
        }
    }
}
